
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class BlogPostModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    name: str = Field("", title="Title", description="")
    website_id: Optional[int] = Field(None, title="Website", description="Restrict publishing to this website.")
    author_id: Optional[int] = Field(None, title="Author", description="")
    blog_id: int = Field(0, title="Blog", description="")
    message_follower_ids: Optional[List[int]] = Field(None, title="Followers", description="")
    message_partner_ids: Optional[List[int]] = Field(None, title="Followers (Partners)", description="")
    message_ids: Optional[List[int]] = Field(None, title="Messages", description="")
    rating_ids: Optional[List[int]] = Field(None, title="Ratings", description="")
    website_message_ids: Optional[List[int]] = Field(None, title="Website Messages", description="Website communication history")
    tag_ids: Optional[List[int]] = Field(None, title="Tags", description="")
    cover_properties: Optional[Any] = Field(None, title="Cover Properties", description="")
    website_published: Optional[bool] = Field(None, title="Visible on current website", description="")
    is_published: Optional[bool] = Field(None, title="Is Published", description="")
    can_publish: Optional[bool] = Field(None, title="Can Publish", description="")
    website_url: Optional[str] = Field(None, title="Website URL", description="The full URL to access the document through the website.")
    is_seo_optimized: Optional[bool] = Field(None, title="SEO optimized", description="")
    website_meta_title: Optional[str] = Field(None, title="Website meta title", description="")
    website_meta_description: Optional[Any] = Field(None, title="Website meta description", description="")
    website_meta_keywords: Optional[str] = Field(None, title="Website meta keywords", description="")
    website_meta_og_img: Optional[str] = Field(None, title="Website opengraph image", description="")
    seo_name: Optional[str] = Field(None, title="Seo name", description="")
    message_is_follower: Optional[bool] = Field(None, title="Is Follower", description="")
    has_message: Optional[bool] = Field(None, title="Has Message", description="")
    message_needaction: Optional[bool] = Field(None, title="Action Needed", description="If checked, new messages require your attention.")
    message_needaction_counter: Optional[int] = Field(None, title="Number of Actions", description="Number of messages requiring action")
    message_has_error: Optional[bool] = Field(None, title="Message Delivery error", description="If checked, some messages have a delivery error.")
    message_has_error_counter: Optional[int] = Field(None, title="Number of errors", description="Number of messages with delivery error")
    message_attachment_count: Optional[int] = Field(None, title="Attachment Count", description="")
    message_has_sms_error: Optional[bool] = Field(None, title="SMS Delivery error", description="If checked, some messages have a delivery error.")
    subtitle: Optional[str] = Field(None, title="Sub Title", description="")
    author_avatar: Optional[Any] = Field(None, title="Avatar", description="")
    author_name: Optional[str] = Field(None, title="Author Name", description="")
    active: Optional[bool] = Field(None, title="Active", description="")
    content: Optional[Any] = Field(None, title="Content", description="")
    teaser: Optional[Any] = Field(None, title="Teaser", description="")
    teaser_manual: Optional[Any] = Field(None, title="Teaser Content", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    published_date: Optional[str] = Field(None, title="Published Date", description="")
    post_date: Optional[str] = Field(None, title="Publishing date", description="The blog post will be visible for your visitors as of this date on the website if it is set as published.")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")
    write_uid: Optional[int] = Field(None, title="Last Contributor", description="")
    visits: Optional[int] = Field(None, title="No of Views", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")

