
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class CompaniesModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    name: str = Field("", title="Company Name", description="")
    layout_background: Any = Field(None, title="Layout Background", description="")
    parent_id: Optional[int] = Field(None, title="Parent Company", description="")
    root_id: Optional[int] = Field(None, title="Root", description="")
    partner_id: int = Field(0, title="Partner", description="")
    currency_id: int = Field(0, title="Currency", description="")
    state_id: Optional[int] = Field(None, title="Fed. State", description="")
    country_id: Optional[int] = Field(None, title="Country", description="")
    paperformat_id: Optional[int] = Field(None, title="Paper format", description="")
    external_report_layout_id: Optional[int] = Field(None, title="Document Template", description="")
    nomenclature_id: Optional[int] = Field(None, title="Nomenclature", description="")
    resource_calendar_id: Optional[int] = Field(None, title="Default Working Hours", description="")
    alias_domain_id: Optional[int] = Field(None, title="Email Domain", description="")
    website_id: Optional[int] = Field(None, title="Website", description="")
    child_ids: Optional[List[int]] = Field(None, title="Branches", description="")
    all_child_ids: Optional[List[int]] = Field(None, title="All Child", description="")
    parent_ids: Optional[List[int]] = Field(None, title="Parent", description="")
    user_ids: Optional[List[int]] = Field(None, title="Accepted Users", description="")
    bank_ids: Optional[List[int]] = Field(None, title="Banks", description="")
    resource_calendar_ids: Optional[List[int]] = Field(None, title="Working Hours", description="")
    active: Optional[bool] = Field(None, title="Active", description="")
    sequence: Optional[int] = Field(None, title="Sequence", description="Used to order Companies in the company switcher")
    parent_path: Optional[str] = Field(None, title="Parent Path", description="")
    report_header: Optional[Any] = Field(None, title="Company Tagline", description="Company tagline, which is included in a printed document's header or footer (depending on the selected layout).")
    report_footer: Optional[Any] = Field(None, title="Report Footer", description="Footer text displayed at the bottom of all reports.")
    company_details: Optional[Any] = Field(None, title="Company Details", description="Header text displayed at the top of all reports.")
    is_company_details_empty: Optional[bool] = Field(None, title="Is Company Details Empty", description="")
    logo: Optional[Any] = Field(None, title="Company Logo", description="")
    logo_web: Optional[Any] = Field(None, title="Logo Web", description="")
    uses_default_logo: Optional[bool] = Field(None, title="Uses Default Logo", description="")
    street: Optional[str] = Field(None, title="Street", description="")
    street2: Optional[str] = Field(None, title="Street2", description="")
    zip: Optional[str] = Field(None, title="Zip", description="")
    city: Optional[str] = Field(None, title="City", description="")
    email: Optional[str] = Field(None, title="Email", description="")
    phone: Optional[str] = Field(None, title="Phone", description="")
    mobile: Optional[str] = Field(None, title="Mobile", description="")
    website: Optional[str] = Field(None, title="Website Link", description="")
    vat: Optional[str] = Field(None, title="Tax ID", description="The Tax Identification Number. Values here will be validated based on the country format. You can use '/' to indicate that the partner is not subject to tax.")
    company_registry: Optional[str] = Field(None, title="Company ID", description="The registry number of the company. Use it if it is different from the Tax ID. It must be unique across all partners of a same country")
    font: Optional[Any] = Field(None, title="Font", description="")
    primary_color: Optional[str] = Field(None, title="Primary Color", description="")
    secondary_color: Optional[str] = Field(None, title="Secondary Color", description="")
    color: Optional[int] = Field(None, title="Color", description="")
    layout_background_image: Optional[Any] = Field(None, title="Background Image", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")
    social_twitter: Optional[str] = Field(None, title="Twitter Account", description="")
    social_facebook: Optional[str] = Field(None, title="Facebook Account", description="")
    social_github: Optional[str] = Field(None, title="GitHub Account", description="")
    social_linkedin: Optional[str] = Field(None, title="LinkedIn Account", description="")
    social_youtube: Optional[str] = Field(None, title="Youtube Account", description="")
    social_instagram: Optional[str] = Field(None, title="Instagram Account", description="")
    social_tiktok: Optional[str] = Field(None, title="TikTok Account", description="")
    alias_domain_name: Optional[str] = Field(None, title="Alias Domain Name", description="Email domain e.g. 'example.com' in 'odoo@example.com'")
    bounce_email: Optional[str] = Field(None, title="Bounce Email", description="")
    bounce_formatted: Optional[str] = Field(None, title="Bounce", description="")
    catchall_email: Optional[str] = Field(None, title="Catchall Email", description="")
    catchall_formatted: Optional[str] = Field(None, title="Catchall", description="")
    default_from_email: Optional[str] = Field(None, title="Default From", description="")
    email_formatted: Optional[str] = Field(None, title="Formatted Email", description="")
    email_primary_color: Optional[str] = Field(None, title="Email Header Color", description="")
    email_secondary_color: Optional[str] = Field(None, title="Email Button Color", description="")
    partner_gid: Optional[int] = Field(None, title="Company database ID", description="")
    iap_enrich_auto_done: Optional[bool] = Field(None, title="Enrich Done", description="")
    snailmail_color: Optional[bool] = Field(None, title="Snailmail Color", description="")
    snailmail_cover: Optional[bool] = Field(None, title="Add a Cover Page", description="")
    snailmail_duplex: Optional[bool] = Field(None, title="Both sides", description="")
    payment_onboarding_payment_method: Optional[Any] = Field(None, title="Selected onboarding payment method", description="")

