
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class ConfigSettingsModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    company_id: int = Field(0, title="Company", description="")
    external_report_layout_id: Optional[int] = Field(None, title="Document Template", description="")
    geoloc_provider_id: Optional[int] = Field(None, title="API", description="")
    alias_domain_id: Optional[int] = Field(None, title="Alias Domain", description="If you have setup a catch-all email domain redirected to the Odoo server, enter the domain name here.")
    auth_signup_template_user_id: Optional[int] = Field(None, title="Template user for new users created through signup", description="")
    unsplash_app_id: Optional[str] = Field(None, title="Application ID", description="")
    digest_id: Optional[int] = Field(None, title="Digest Email", description="")
    website_id: Optional[int] = Field(None, title="website", description="")
    website_company_id: Optional[int] = Field(None, title="Website Company", description="")
    website_default_lang_id: Optional[int] = Field(None, title="Default language", description="")
    channel_id: Optional[int] = Field(None, title="Website Live Channel", description="")
    language_ids: Optional[List[int]] = Field(None, title="Languages", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")
    web_app_name: Optional[str] = Field(None, title="Web App Name", description="")
    is_root_company: Optional[bool] = Field(None, title="Is Root Company", description="")
    user_default_rights: Optional[bool] = Field(None, title="Default Access Rights", description="")
    module_base_import: Optional[bool] = Field(None, title="Allow users to import data from CSV/XLS/XLSX/ODS files", description="")
    module_google_calendar: Optional[bool] = Field(None, title="Allow the users to synchronize their calendar  with Google Calendar", description="")
    module_microsoft_calendar: Optional[bool] = Field(None, title="Allow the users to synchronize their calendar with Outlook Calendar", description="")
    module_mail_plugin: Optional[bool] = Field(None, title="Allow integration with the mail plugins", description="")
    module_auth_oauth: Optional[bool] = Field(None, title="Use external authentication providers (OAuth)", description="")
    module_auth_ldap: Optional[bool] = Field(None, title="LDAP Authentication", description="")
    module_account_inter_company_rules: Optional[bool] = Field(None, title="Manage Inter Company", description="")
    module_voip: Optional[bool] = Field(None, title="Asterisk (VoIP)", description="")
    module_web_unsplash: Optional[bool] = Field(None, title="Unsplash Image Library", description="")
    module_partner_autocomplete: Optional[bool] = Field(None, title="Partner Autocomplete", description="")
    module_base_geolocalize: Optional[bool] = Field(None, title="GeoLocalize", description="")
    module_google_recaptcha: Optional[bool] = Field(None, title="reCAPTCHA", description="")
    module_website_cf_turnstile: Optional[bool] = Field(None, title="Cloudflare Turnstile", description="")
    report_footer: Optional[Any] = Field(None, title="Custom Report Footer", description="Footer text displayed at the bottom of all reports.")
    group_multi_currency: Optional[bool] = Field(None, title="Multi-Currencies", description="Allows to work in a multi currency environment")
    show_effect: Optional[bool] = Field(None, title="Show Effect", description="")
    company_count: Optional[int] = Field(None, title="Number of Companies", description="")
    active_user_count: Optional[int] = Field(None, title="Number of Active Users", description="")
    language_count: Optional[int] = Field(None, title="Number of Languages", description="")
    company_name: Optional[str] = Field(None, title="Company Name", description="")
    company_informations: Optional[Any] = Field(None, title="Company Informations", description="")
    company_country_code: Optional[str] = Field(None, title="Company Country Code", description="The ISO country code in two chars. \nYou can use this field for quick search.")
    profiling_enabled_until: Optional[str] = Field(None, title="Profiling enabled until", description="")
    module_product_images: Optional[bool] = Field(None, title="Get product pictures using barcode", description="")
    geoloc_provider_techname: Optional[str] = Field(None, title="Technical Name", description="")
    geoloc_provider_googlemap_key: Optional[str] = Field(None, title="Google Map API Key", description="Visit https://developers.google.com/maps/documentation/geocoding/get-api-key for more information.")
    recaptcha_public_key: Optional[str] = Field(None, title="Site Key", description="")
    recaptcha_private_key: Optional[str] = Field(None, title="Secret Key", description="")
    recaptcha_min_score: Optional[Any] = Field(None, title="Minimum score", description="By default, should be one of 0.1, 0.3, 0.7, 0.9.\n1.0 is very likely a good interaction, 0.0 is very likely a bot")
    external_email_server_default: Optional[bool] = Field(None, title="Use Custom Email Servers", description="")
    fail_counter: Optional[int] = Field(None, title="Fail Mail", description="")
    module_google_gmail: Optional[bool] = Field(None, title="Support Gmail Authentication", description="")
    module_microsoft_outlook: Optional[bool] = Field(None, title="Support Outlook Authentication", description="")
    restrict_template_rendering: Optional[bool] = Field(None, title="Restrict Template Rendering", description="Users will still be able to render templates.\nHowever only Mail Template Editors will be able to create new dynamic templates or modify existing ones.")
    use_twilio_rtc_servers: Optional[bool] = Field(None, title="Use Twilio ICE servers", description="If you want to use twilio as TURN/STUN server provider")
    twilio_account_sid: Optional[str] = Field(None, title="Twilio Account SID", description="")
    twilio_account_token: Optional[str] = Field(None, title="Twilio Account Auth Token", description="")
    sfu_server_url: Optional[str] = Field(None, title="SFU Server URL", description="")
    sfu_server_key: Optional[str] = Field(None, title="SFU Server key", description="Base64 encoded key")
    email_primary_color: Optional[str] = Field(None, title="Email Header Color", description="")
    email_secondary_color: Optional[str] = Field(None, title="Email Button Color", description="")
    tenor_api_key: Optional[str] = Field(None, title="Tenor API key", description="Add a Tenor GIF API key to enable GIFs support. https://developers.google.com/tenor/guides/quickstart#setup")
    tenor_content_filter: Optional[Any] = Field(None, title="Tenor content filter", description="https://developers.google.com/tenor/guides/content-filtering")
    tenor_gif_limit: Optional[int] = Field(None, title="Tenor Gif Limit", description="Fetch up to the specified number of GIF.")
    google_translate_api_key: Optional[str] = Field(None, title="Message Translation API Key", description="A valid Google API key is required to enable message translation. https://cloud.google.com/translate/docs/setup")
    group_analytic_accounting: Optional[bool] = Field(None, title="Analytic Accounting", description="")
    auth_signup_reset_password: Optional[bool] = Field(None, title="Enable password reset from Login page", description="")
    auth_signup_uninvited: Optional[Any] = Field(None, title="Customer Account", description="")
    google_gmail_client_identifier: Optional[str] = Field(None, title="Gmail Client Id", description="")
    google_gmail_client_secret: Optional[str] = Field(None, title="Gmail Client Secret", description="")
    group_discount_per_so_line: Optional[bool] = Field(None, title="Discounts", description="")
    group_uom: Optional[bool] = Field(None, title="Units of Measure", description="")
    group_product_variant: Optional[bool] = Field(None, title="Variants", description="")
    module_sale_product_matrix: Optional[bool] = Field(None, title="Sales Grid Entry", description="")
    module_loyalty: Optional[bool] = Field(None, title="Promotions, Coupons, Gift Card & Loyalty Program", description="")
    group_stock_packaging: Optional[bool] = Field(None, title="Product Packagings", description="")
    group_product_pricelist: Optional[bool] = Field(None, title="Pricelists", description="")
    group_sale_pricelist: Optional[bool] = Field(None, title="Advanced Pricelists", description="Allows to manage different prices based on rules per category of customers.\n                Example: 10% for retailers, promotion of 5 EUR on this product, etc.")
    product_pricelist_setting: Optional[Any] = Field(None, title="Pricelists Method", description="Multiple prices: Pricelists with fixed price rules by product,\nAdvanced rules: enables advanced price rules for pricelists.")
    product_weight_in_lbs: Optional[Any] = Field(None, title="Weight unit of measure", description="")
    product_volume_volume_in_cubic_feet: Optional[Any] = Field(None, title="Volume unit of measure", description="")
    unsplash_access_key: Optional[str] = Field(None, title="Access Key", description="")
    partner_autocomplete_insufficient_credit: Optional[bool] = Field(None, title="Insufficient credit", description="")
    portal_allow_api_keys: Optional[bool] = Field(None, title="Customer API Keys", description="")
    snailmail_color: Optional[bool] = Field(None, title="Print In Color", description="")
    snailmail_cover: Optional[bool] = Field(None, title="Add a Cover Page", description="")
    snailmail_duplex: Optional[bool] = Field(None, title="Print Both sides", description="")
    digest_emails: Optional[bool] = Field(None, title="Digest Emails", description="")
    website_name: Optional[str] = Field(None, title="Website Name", description="")
    website_domain: Optional[str] = Field(None, title="Website Domain", description="E.g. https://www.mydomain.com")
    website_homepage_url: Optional[str] = Field(None, title="Homepage Url", description="E.g. /contactus or /shop")
    website_logo: Optional[Any] = Field(None, title="Website Logo", description="Display this logo on the website.")
    website_language_count: Optional[int] = Field(None, title="Number of languages", description="")
    website_default_lang_code: Optional[str] = Field(None, title="Default language code", description="This field is used to set/get locales for user")
    shared_user_account: Optional[bool] = Field(None, title="Shared Customer Accounts", description="")
    website_cookies_bar: Optional[bool] = Field(None, title="Cookies Bar", description="Display a customizable cookies bar on your website.")
    google_analytics_key: Optional[str] = Field(None, title="Google Analytics Key", description="")
    google_search_console: Optional[str] = Field(None, title="Google Search Console", description="Google key, or Enable to access first reply")
    plausible_shared_key: Optional[str] = Field(None, title="Plausible auth Key", description="")
    plausible_site: Optional[str] = Field(None, title="Plausible Site (e.g. domain.com)", description="")
    cdn_activated: Optional[bool] = Field(None, title="Content Delivery Network (CDN)", description="")
    cdn_url: Optional[str] = Field(None, title="CDN Base URL", description="")
    cdn_filters: Optional[Any] = Field(None, title="CDN Filters", description="URL matching those filters will be rewritten using the CDN Base URL")
    favicon: Optional[Any] = Field(None, title="Favicon", description="This field holds the image used to display a favicon on the website.")
    social_default_image: Optional[Any] = Field(None, title="Default Social Share Image", description="If set, replaces the website logo as the default social share image.")
    group_multi_website: Optional[bool] = Field(None, title="Multi-website", description="")
    has_google_analytics: Optional[bool] = Field(None, title="Google Analytics", description="")
    has_google_search_console: Optional[bool] = Field(None, title="Console Google Search", description="")
    has_default_share_image: Optional[bool] = Field(None, title="Use a image by default for sharing", description="")
    has_plausible_shared_key: Optional[bool] = Field(None, title="Plausible Analytics", description="")
    module_website_livechat: Optional[bool] = Field(None, title="Module Website Livechat", description="")
    module_marketing_automation: Optional[bool] = Field(None, title="Module Marketing Automation", description="")

