
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class ContactModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    website_id: Optional[int] = Field(None, title="Website", description="Restrict publishing to this website.")
    activity_user_id: Optional[int] = Field(None, title="Responsible User", description="")
    activity_type_id: Optional[int] = Field(None, title="Next Activity Type", description="")
    parent_id: Optional[int] = Field(None, title="Related Company", description="")
    user_id: Optional[int] = Field(None, title="Salesperson", description="The internal user in charge of this contact.")
    same_vat_partner_id: Optional[int] = Field(None, title="Partner with same Tax ID", description="")
    same_company_registry_partner_id: Optional[int] = Field(None, title="Partner with same Company Registry", description="")
    category_id: Optional[List[int]] = Field(None, title="Tags", description="")
    state_id: Optional[int] = Field(None, title="State", description="")
    country_id: Optional[int] = Field(None, title="Country", description="")
    industry_id: Optional[int] = Field(None, title="Industry", description="")
    company_id: Optional[int] = Field(None, title="Company", description="")
    commercial_partner_id: Optional[int] = Field(None, title="Commercial Entity", description="")
    message_follower_ids: Optional[List[int]] = Field(None, title="Followers", description="")
    message_partner_ids: Optional[List[int]] = Field(None, title="Followers (Partners)", description="")
    message_ids: Optional[List[int]] = Field(None, title="Messages", description="")
    rating_ids: Optional[List[int]] = Field(None, title="Ratings", description="")
    website_message_ids: Optional[List[int]] = Field(None, title="Website Messages", description="Website communication history")
    activity_ids: Optional[List[int]] = Field(None, title="Activities", description="")
    child_ids: Optional[List[int]] = Field(None, title="Contact", description="")
    bank_ids: Optional[List[int]] = Field(None, title="Banks", description="")
    user_ids: Optional[List[int]] = Field(None, title="Users", description="")
    channel_ids: Optional[List[int]] = Field(None, title="Channels", description="")
    starred_message_ids: Optional[List[int]] = Field(None, title="Starred Message", description="")
    payment_token_ids: Optional[List[int]] = Field(None, title="Payment Tokens", description="")
    visitor_ids: Optional[List[int]] = Field(None, title="Visitors", description="")
    is_seo_optimized: Optional[bool] = Field(None, title="SEO optimized", description="")
    website_meta_title: Optional[str] = Field(None, title="Website meta title", description="")
    website_meta_description: Optional[Any] = Field(None, title="Website meta description", description="")
    website_meta_keywords: Optional[str] = Field(None, title="Website meta keywords", description="")
    website_meta_og_img: Optional[str] = Field(None, title="Website opengraph image", description="")
    seo_name: Optional[str] = Field(None, title="Seo name", description="")
    website_published: Optional[bool] = Field(None, title="Visible on current website", description="")
    is_published: Optional[bool] = Field(None, title="Is Published", description="")
    can_publish: Optional[bool] = Field(None, title="Can Publish", description="")
    website_url: Optional[str] = Field(None, title="Website URL", description="The full URL to access the document through the website.")
    message_is_follower: Optional[bool] = Field(None, title="Is Follower", description="")
    has_message: Optional[bool] = Field(None, title="Has Message", description="")
    message_needaction: Optional[bool] = Field(None, title="Action Needed", description="If checked, new messages require your attention.")
    message_needaction_counter: Optional[int] = Field(None, title="Number of Actions", description="Number of messages requiring action")
    message_has_error: Optional[bool] = Field(None, title="Message Delivery error", description="If checked, some messages have a delivery error.")
    message_has_error_counter: Optional[int] = Field(None, title="Number of errors", description="Number of messages with delivery error")
    message_attachment_count: Optional[int] = Field(None, title="Attachment Count", description="")
    message_has_sms_error: Optional[bool] = Field(None, title="SMS Delivery error", description="If checked, some messages have a delivery error.")
    email_normalized: Optional[str] = Field(None, title="Normalized Email", description="This field is used to search on email address as the primary email field can contain more than strictly an email address.")
    is_blacklisted: Optional[bool] = Field(None, title="Blacklist", description="If the email address is on the blacklist, the contact won't receive mass mailing anymore, from any list")
    message_bounce: Optional[int] = Field(None, title="Bounce", description="Counter of the number of bounced emails for this contact")
    activity_state: Optional[Any] = Field(None, title="Activity State", description="Status based on activities\nOverdue: Due date is already passed\nToday: Activity date is today\nPlanned: Future activities.")
    activity_type_icon: Optional[str] = Field(None, title="Activity Type Icon", description="Font awesome icon e.g. fa-tasks")
    activity_date_deadline: Optional[str] = Field(None, title="Next Activity Deadline", description="")
    my_activity_date_deadline: Optional[str] = Field(None, title="My Activity Deadline", description="")
    activity_summary: Optional[str] = Field(None, title="Next Activity Summary", description="")
    activity_exception_decoration: Optional[Any] = Field(None, title="Activity Exception Decoration", description="Type of the exception activity on record.")
    activity_exception_icon: Optional[str] = Field(None, title="Icon", description="Icon to indicate an exception activity.")
    image_1920: Optional[Any] = Field(None, title="Image", description="")
    image_1024: Optional[Any] = Field(None, title="Image 1024", description="")
    image_512: Optional[Any] = Field(None, title="Image 512", description="")
    image_256: Optional[Any] = Field(None, title="Image 256", description="")
    image_128: Optional[Any] = Field(None, title="Image 128", description="")
    avatar_1920: Optional[Any] = Field(None, title="Avatar", description="")
    avatar_1024: Optional[Any] = Field(None, title="Avatar 1024", description="")
    avatar_512: Optional[Any] = Field(None, title="Avatar 512", description="")
    avatar_256: Optional[Any] = Field(None, title="Avatar 256", description="")
    avatar_128: Optional[Any] = Field(None, title="Avatar 128", description="")
    name: Optional[str] = Field(None, title="Name", description="")
    complete_name: Optional[str] = Field(None, title="Complete Name", description="")
    date: Optional[str] = Field(None, title="Date", description="")
    title: Optional[int] = Field(None, title="Title", description="")
    parent_name: Optional[str] = Field(None, title="Parent name", description="")
    ref: Optional[str] = Field(None, title="Reference", description="")
    lang: Optional[Any] = Field(None, title="Language", description="All the emails and documents sent to this contact will be translated in this language.")
    active_lang_count: Optional[int] = Field(None, title="Active Lang Count", description="")
    tz: Optional[Any] = Field(None, title="Timezone", description="When printing documents and exporting/importing data, time values are computed according to this timezone.\nIf the timezone is not set, UTC (Coordinated Universal Time) is used.\nAnywhere else, time values are computed according to the time offset of your web client.")
    tz_offset: Optional[str] = Field(None, title="Timezone offset", description="")
    vat: Optional[str] = Field(None, title="Tax ID", description="The Tax Identification Number. Values here will be validated based on the country format. You can use '/' to indicate that the partner is not subject to tax.")
    company_registry: Optional[str] = Field(None, title="Company ID", description="The registry number of the company. Use it if it is different from the Tax ID. It must be unique across all partners of a same country")
    website: Optional[str] = Field(None, title="Website Link", description="")
    comment: Optional[Any] = Field(None, title="Notes", description="")
    active: Optional[bool] = Field(None, title="Active", description="")
    employee: Optional[bool] = Field(None, title="Employee", description="Check this box if this contact is an Employee.")
    function: Optional[str] = Field(None, title="Job Position", description="")
    type: Optional[Any] = Field(None, title="Address Type", description="- Contact: Use this to organize the contact details of employees of a given company (e.g. CEO, CFO, ...).\n- Invoice Address: Preferred address for all invoices. Selected by default when you invoice an order that belongs to this company.\n- Delivery Address: Preferred address for all deliveries. Selected by default when you deliver an order that belongs to this company.\n- Other: Other address for the company (e.g. subsidiary, ...)")
    street: Optional[str] = Field(None, title="Street", description="")
    street2: Optional[str] = Field(None, title="Street2", description="")
    zip: Optional[str] = Field(None, title="Zip", description="")
    city: Optional[str] = Field(None, title="City", description="")
    country_code: Optional[str] = Field(None, title="Country Code", description="The ISO country code in two chars. \nYou can use this field for quick search.")
    partner_latitude: Optional[Any] = Field(None, title="Geo Latitude", description="")
    partner_longitude: Optional[Any] = Field(None, title="Geo Longitude", description="")
    email: Optional[str] = Field(None, title="Email", description="")
    email_formatted: Optional[str] = Field(None, title="Formatted Email", description="Format email address \"Name <email@domain>\"")
    phone: Optional[str] = Field(None, title="Phone", description="")
    mobile: Optional[str] = Field(None, title="Mobile", description="")
    is_company: Optional[bool] = Field(None, title="Is a Company", description="Check if the contact is a company, otherwise it is a person")
    is_public: Optional[bool] = Field(None, title="Is Public", description="")
    company_type: Optional[Any] = Field(None, title="Company Type", description="")
    color: Optional[int] = Field(None, title="Color Index", description="")
    partner_share: Optional[bool] = Field(None, title="Share Partner", description="Either customer (not a user), either shared user. Indicated the current partner is a customer without access or with a limited access created for sharing data.")
    contact_address: Optional[str] = Field(None, title="Complete Address", description="")
    commercial_company_name: Optional[str] = Field(None, title="Company Name Entity", description="")
    company_name: Optional[str] = Field(None, title="Company Name", description="")
    barcode: Optional[str] = Field(None, title="Barcode", description="Use a barcode to identify this contact.")
    self: Optional[int] = Field(None, title="Self", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")
    im_status: Optional[str] = Field(None, title="IM Status", description="")
    date_localization: Optional[str] = Field(None, title="Geolocation Date", description="")
    contact_address_inline: Optional[str] = Field(None, title="Inlined Complete Address", description="")
    signup_token: Optional[str] = Field(None, title="Signup Token", description="")
    signup_type: Optional[str] = Field(None, title="Signup Token Type", description="")
    signup_expiration: Optional[str] = Field(None, title="Signup Expiration", description="")
    signup_valid: Optional[bool] = Field(None, title="Signup Token is Valid", description="")
    signup_url: Optional[str] = Field(None, title="Signup URL", description="")
    property_product_pricelist: Optional[int] = Field(None, title="Pricelist", description="This pricelist will be used, instead of the default one, for sales to the current partner")
    partner_gid: Optional[int] = Field(None, title="Company database ID", description="")
    additional_info: Optional[str] = Field(None, title="Additional info", description="")
    phone_sanitized: Optional[str] = Field(None, title="Sanitized Number", description="Field used to store sanitized phone number. Helps speeding up searches and comparisons.")
    phone_sanitized_blacklisted: Optional[bool] = Field(None, title="Phone Blacklisted", description="If the sanitized phone number is on the blacklist, the contact won't receive mass mailing sms anymore, from any list")
    phone_blacklisted: Optional[bool] = Field(None, title="Blacklisted Phone is Phone", description="Indicates if a blacklisted sanitized phone number is a phone number. Helps distinguish which number is blacklisted             when there is both a mobile and phone field in a model.")
    mobile_blacklisted: Optional[bool] = Field(None, title="Blacklisted Phone Is Mobile", description="Indicates if a blacklisted sanitized phone number is a mobile number. Helps distinguish which number is blacklisted             when there is both a mobile and phone field in a model.")
    phone_mobile_search: Optional[str] = Field(None, title="Phone/Mobile", description="")
    payment_token_count: Optional[int] = Field(None, title="Payment Token Count", description="")
    user_livechat_username: Optional[str] = Field(None, title="User Livechat Username", description="")
    website_description: Optional[Any] = Field(None, title="Website Partner Full Description", description="")
    website_short_description: Optional[Any] = Field(None, title="Website Partner Short Description", description="")

