
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class EmailcompositionwizardModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    message_type: Any = Field(None, title="Type", description="Message type: email for email message, notification for system message, comment for other messages such as user replies")
    template_id: Optional[int] = Field(None, title="Use template", description="")
    parent_id: Optional[int] = Field(None, title="Parent Message", description="")
    author_id: Optional[int] = Field(None, title="Author", description="Author of the message. If not set, email_from may hold an email address that did not match any partner.")
    res_domain_user_id: Optional[int] = Field(None, title="Responsible", description="Used as context used to evaluate composer domain")
    record_alias_domain_id: Optional[int] = Field(None, title="Alias Domain", description="")
    record_company_id: Optional[int] = Field(None, title="Company", description="")
    subtype_id: Optional[int] = Field(None, title="Subtype", description="")
    mail_activity_type_id: Optional[int] = Field(None, title="Mail Activity Type", description="")
    mail_server_id: Optional[int] = Field(None, title="Outgoing mail server", description="")
    attachment_ids: Optional[List[int]] = Field(None, title="Attachments", description="")
    res_ids: Optional[Any] = Field(None, title="Related Document IDs", description="")
    partner_ids: Optional[List[int]] = Field(None, title="Additional Contacts", description="")
    lang: Optional[str] = Field(None, title="Language", description="Optional translation language (ISO code) to select when sending out an email. If not set, the english version will be used. This should usually be a placeholder expression that provides the appropriate language, e.g. {{ object.partner_id.lang }}.")
    render_model: Optional[str] = Field(None, title="Rendering Model", description="")
    subject: Optional[str] = Field(None, title="Subject", description="")
    body: Optional[Any] = Field(None, title="Contents", description="")
    body_has_template_value: Optional[bool] = Field(None, title="Body content is the same as the template", description="")
    is_mail_template_editor: Optional[bool] = Field(None, title="Is Editor", description="")
    can_edit_body: Optional[bool] = Field(None, title="Can Edit Body", description="")
    email_layout_xmlid: Optional[str] = Field(None, title="Email Notification Layout", description="")
    email_add_signature: Optional[bool] = Field(None, title="Add signature", description="")
    email_from: Optional[str] = Field(None, title="From", description="Email address of the sender. This field is set when no matching partner is found and replaces the author_id field in the chatter.")
    composition_mode: Optional[Any] = Field(None, title="Composition mode", description="")
    composition_batch: Optional[bool] = Field(None, title="Batch composition", description="")
    model: Optional[str] = Field(None, title="Related Document Model", description="")
    model_is_thread: Optional[bool] = Field(None, title="Thread-Enabled", description="")
    res_domain: Optional[Any] = Field(None, title="Active domain", description="")
    record_name: Optional[str] = Field(None, title="Record Name", description="")
    subtype_is_log: Optional[bool] = Field(None, title="Is a log", description="")
    reply_to: Optional[str] = Field(None, title="Reply To", description="Reply email address. Setting the reply_to bypasses the automatic thread creation.")
    reply_to_force_new: Optional[bool] = Field(None, title="Considers answers as new thread", description="Manage answers as new incoming emails instead of replies going to the same thread.")
    reply_to_mode: Optional[Any] = Field(None, title="Replies", description="Original Discussion: Answers go in the original document discussion thread. \n Another Email Address: Answers go to the email address mentioned in the tracking message-id instead of original document discussion thread. \n This has an impact on the generated message-id.")
    auto_delete: Optional[bool] = Field(None, title="Delete Emails", description="This option permanently removes any track of email after it's been sent, including from the Technical menu in the Settings, in order to preserve storage space of your Odoo database.")
    auto_delete_keep_log: Optional[bool] = Field(None, title="Keep Message Copy", description="Keep a copy of the email content if emails are removed (mass mailing only)")
    force_send: Optional[bool] = Field(None, title="Send mailing or notifications directly", description="")
    scheduled_date: Optional[str] = Field(None, title="Scheduled Date", description="In comment mode: if set, postpone notifications sending. In mass mail mode: if sent, send emails after that date. This date is considered as being in UTC timezone.")
    use_exclusion_list: Optional[bool] = Field(None, title="Check Exclusion List", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")

