
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class EmailTemplatesModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    model_id: Optional[int] = Field(None, title="Applies to", description="")
    user_id: Optional[int] = Field(None, title="User", description="The template belongs to this user")
    mail_server_id: Optional[int] = Field(None, title="Outgoing Mail Server", description="Optional preferred server for outgoing mails. If not set, the highest priority one will be used.")
    attachment_ids: Optional[List[int]] = Field(None, title="Attachments", description="You may attach files to this template, to be added to all emails created from this template")
    report_template_ids: Optional[List[int]] = Field(None, title="Dynamic Reports", description="")
    template_fs: Optional[str] = Field(None, title="Template Filename", description="File from where the template originates. Used to reset broken template.")
    lang: Optional[str] = Field(None, title="Language", description="Optional translation language (ISO code) to select when sending out an email. If not set, the english version will be used. This should usually be a placeholder expression that provides the appropriate language, e.g. {{ object.partner_id.lang }}.")
    render_model: Optional[str] = Field(None, title="Rendering Model", description="")
    name: Optional[str] = Field(None, title="Name", description="")
    description: Optional[Any] = Field(None, title="Template description", description="This field is used for internal description of the template's usage.")
    active: Optional[bool] = Field(None, title="Active", description="")
    template_category: Optional[Any] = Field(None, title="Template Category", description="")
    model: Optional[str] = Field(None, title="Related Document Model", description="")
    subject: Optional[str] = Field(None, title="Subject", description="Subject (placeholders may be used here)")
    email_from: Optional[str] = Field(None, title="From", description="Sender address (placeholders may be used here). If not set, the default value will be the author's email alias if configured, or email address.")
    use_default_to: Optional[bool] = Field(None, title="Default recipients", description="Default recipients of the record:\n- partner (using id on a partner or the partner_id field) OR\n- email (using email_from or email field)")
    email_to: Optional[str] = Field(None, title="To (Emails)", description="Comma-separated recipient addresses (placeholders may be used here)")
    partner_to: Optional[str] = Field(None, title="To (Partners)", description="Comma-separated ids of recipient partners (placeholders may be used here)")
    email_cc: Optional[str] = Field(None, title="Cc", description="Carbon copy recipients (placeholders may be used here)")
    reply_to: Optional[str] = Field(None, title="Reply To", description="Email address to which replies will be redirected when sending emails in mass; only used when the reply is not logged in the original discussion thread.")
    body_html: Optional[Any] = Field(None, title="Body", description="")
    email_layout_xmlid: Optional[str] = Field(None, title="Email Notification Layout", description="")
    scheduled_date: Optional[str] = Field(None, title="Scheduled Date", description="If set, the queue manager will send the email after the date. If not set, the email will be send as soon as possible. You can use dynamic expression.")
    auto_delete: Optional[bool] = Field(None, title="Auto Delete", description="This option permanently removes any track of email after it's been sent, including from the Technical menu in the Settings, in order to preserve storage space of your Odoo database.")
    ref_ir_act_window: Optional[int] = Field(None, title="Sidebar action", description="Sidebar action to make this template available on records of the related document model")
    can_write: Optional[bool] = Field(None, title="Can Write", description="The current user can edit the template.")
    is_template_editor: Optional[bool] = Field(None, title="Is Template Editor", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")

