
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class ModuleModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    name: str = Field("", title="Technical Name", description="")
    category_id: Optional[int] = Field(None, title="Category", description="")
    dependencies_id: Optional[List[int]] = Field(None, title="Dependencies", description="")
    exclusion_ids: Optional[List[int]] = Field(None, title="Exclusions", description="")
    image_ids: Optional[List[int]] = Field(None, title="Screenshots", description="")
    shortdesc: Optional[str] = Field(None, title="Module Name", description="")
    summary: Optional[str] = Field(None, title="Summary", description="")
    description: Optional[Any] = Field(None, title="Description", description="")
    description_html: Optional[Any] = Field(None, title="Description HTML", description="")
    author: Optional[str] = Field(None, title="Author", description="")
    maintainer: Optional[str] = Field(None, title="Maintainer", description="")
    contributors: Optional[Any] = Field(None, title="Contributors", description="")
    website: Optional[str] = Field(None, title="Website", description="")
    installed_version: Optional[str] = Field(None, title="Latest Version", description="")
    latest_version: Optional[str] = Field(None, title="Installed Version", description="")
    published_version: Optional[str] = Field(None, title="Published Version", description="")
    url: Optional[str] = Field(None, title="URL", description="")
    sequence: Optional[int] = Field(None, title="Sequence", description="")
    auto_install: Optional[bool] = Field(None, title="Automatic Installation", description="An auto-installable module is automatically installed by the system when all its dependencies are satisfied. If the module has no dependency, it is always installed.")
    state: Optional[Any] = Field(None, title="Status", description="")
    demo: Optional[bool] = Field(None, title="Demo Data", description="")
    license: Optional[Any] = Field(None, title="License", description="")
    menus_by_module: Optional[Any] = Field(None, title="Menus", description="")
    reports_by_module: Optional[Any] = Field(None, title="Reports", description="")
    views_by_module: Optional[Any] = Field(None, title="Views", description="")
    application: Optional[bool] = Field(None, title="Application", description="")
    icon: Optional[str] = Field(None, title="Icon URL", description="")
    icon_image: Optional[Any] = Field(None, title="Icon", description="")
    icon_flag: Optional[str] = Field(None, title="Flag", description="")
    to_buy: Optional[bool] = Field(None, title="Odoo Enterprise Module", description="")
    has_iap: Optional[bool] = Field(None, title="Has Iap", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")
    imported: Optional[bool] = Field(None, title="Imported Module", description="")
    module_type: Optional[Any] = Field(None, title="Module Type", description="")
    is_installed_on_current_website: Optional[bool] = Field(None, title="Is Installed On Current Website", description="")

