
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class PartnerWebPushDeviceModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    endpoint: str = Field("", title="Browser endpoint", description="")
    keys: str = Field("", title="Browser keys", description="It's refer to browser keys used by the notification: \n- p256dh: It's the subscription public key generated by the browser. The browser will \n          keep the private key secret and use it for decrypting the payload\n- auth: The auth value should be treated as a secret and not shared outside of Odoo")
    partner_id: int = Field(0, title="Partner", description="")
    expiration_time: Optional[str] = Field(None, title="Expiration Token Date", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")

