
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class PaymentProviderModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    name: str = Field("", title="Name", description="")
    code: Any = Field(None, title="Code", description="The technical code of this payment provider.")
    state: Any = Field(None, title="State", description="In test mode, a fake payment is processed through a test payment interface.\nThis mode is advised when setting up the provider.")
    company_id: int = Field(0, title="Company", description="")
    main_currency_id: Optional[int] = Field(None, title="Currency", description="The main currency of the company, used to display monetary fields.")
    redirect_form_view_id: Optional[int] = Field(None, title="Redirect Form Template", description="The template rendering a form submitted to redirect the user when making a payment")
    inline_form_view_id: Optional[int] = Field(None, title="Inline Form Template", description="The template rendering the inline payment form when making a direct payment")
    token_inline_form_view_id: Optional[int] = Field(None, title="Token Inline Form Template", description="The template rendering the inline payment form when making a payment by token.")
    express_checkout_form_view_id: Optional[int] = Field(None, title="Express Checkout Form Template", description="The template rendering the express payment methods' form.")
    module_id: Optional[int] = Field(None, title="Corresponding Module", description="")
    payment_method_ids: Optional[List[int]] = Field(None, title="Supported Payment Methods", description="")
    available_country_ids: Optional[List[int]] = Field(None, title="Countries", description="The countries in which this payment provider is available. Leave blank to make it available in all countries.")
    available_currency_ids: Optional[List[int]] = Field(None, title="Currencies", description="The currencies available with this payment provider. Leave empty not to restrict any.")
    sequence: Optional[int] = Field(None, title="Sequence", description="Define the display order")
    is_published: Optional[bool] = Field(None, title="Published", description="Whether the provider is visible on the website or not. Tokens remain functional but are only visible on manage forms.")
    allow_tokenization: Optional[bool] = Field(None, title="Allow Saving Payment Methods", description="This controls whether customers can save their payment methods as payment tokens.\nA payment token is an anonymous link to the payment method details saved in the\nprovider's database, allowing the customer to reuse it for a next purchase.")
    capture_manually: Optional[bool] = Field(None, title="Capture Amount Manually", description="Capture the amount from Odoo, when the delivery is completed.\nUse this if you want to charge your customers cards only when\nyou are sure you can ship the goods to them.")
    allow_express_checkout: Optional[bool] = Field(None, title="Allow Express Checkout", description="This controls whether customers can use express payment methods. Express checkout enables customers to pay with Google Pay and Apple Pay from which address information is collected at payment.")
    maximum_amount: Optional[float] = Field(None, title="Maximum Amount", description="The maximum payment amount that this payment provider is available for. Leave blank to make it available for any payment amount.")
    pre_msg: Optional[Any] = Field(None, title="Help Message", description="The message displayed to explain and help the payment process")
    pending_msg: Optional[Any] = Field(None, title="Pending Message", description="The message displayed if the order pending after the payment process")
    auth_msg: Optional[Any] = Field(None, title="Authorize Message", description="The message displayed if payment is authorized")
    done_msg: Optional[Any] = Field(None, title="Done Message", description="The message displayed if the order is successfully done after the payment process")
    cancel_msg: Optional[Any] = Field(None, title="Canceled Message", description="The message displayed if the order is canceled during the payment process")
    support_tokenization: Optional[bool] = Field(None, title="Tokenization Supported", description="")
    support_manual_capture: Optional[Any] = Field(None, title="Manual Capture Supported", description="")
    support_express_checkout: Optional[bool] = Field(None, title="Express Checkout Supported", description="")
    support_refund: Optional[Any] = Field(None, title="Type of Refund Supported", description="")
    image_128: Optional[Any] = Field(None, title="Image", description="")
    color: Optional[int] = Field(None, title="Color", description="The color of the card in kanban view")
    module_state: Optional[Any] = Field(None, title="Installation State", description="")
    module_to_buy: Optional[bool] = Field(None, title="Odoo Enterprise Module", description="")
    show_credentials_page: Optional[bool] = Field(None, title="Show Credentials Page", description="")
    show_allow_tokenization: Optional[bool] = Field(None, title="Show Allow Tokenization", description="")
    show_allow_express_checkout: Optional[bool] = Field(None, title="Show Allow Express Checkout", description="")
    show_pre_msg: Optional[bool] = Field(None, title="Show Pre Msg", description="")
    show_pending_msg: Optional[bool] = Field(None, title="Show Pending Msg", description="")
    show_auth_msg: Optional[bool] = Field(None, title="Show Auth Msg", description="")
    show_done_msg: Optional[bool] = Field(None, title="Show Done Msg", description="")
    show_cancel_msg: Optional[bool] = Field(None, title="Show Cancel Msg", description="")
    require_currency: Optional[bool] = Field(None, title="Require Currency", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")

