
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class ProductModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    name: str = Field("", title="Name", description="")
    detailed_type: Any = Field(None, title="Product Type", description="A storable product is a product for which you manage stock. The Inventory app has to be installed.\nA consumable product is a product for which stock is not managed.\nA service is a non-material product you provide.")
    activity_user_id: Optional[int] = Field(None, title="Responsible User", description="")
    activity_type_id: Optional[int] = Field(None, title="Next Activity Type", description="")
    categ_id: int = Field(0, title="Product Category", description="")
    currency_id: Optional[int] = Field(None, title="Currency", description="")
    cost_currency_id: Optional[int] = Field(None, title="Cost Currency", description="")
    uom_id: int = Field(0, title="Unit of Measure", description="Default unit of measure used for all stock operations.")
    uom_po_id: int = Field(0, title="Purchase UoM", description="Default unit of measure used for purchase orders. It must be in the same category as the default unit of measure.")
    company_id: Optional[int] = Field(None, title="Company", description="")
    product_variant_id: Optional[int] = Field(None, title="Product", description="")
    activity_ids: Optional[List[int]] = Field(None, title="Activities", description="")
    message_follower_ids: Optional[List[int]] = Field(None, title="Followers", description="")
    message_partner_ids: Optional[List[int]] = Field(None, title="Followers (Partners)", description="")
    message_ids: Optional[List[int]] = Field(None, title="Messages", description="")
    rating_ids: Optional[List[int]] = Field(None, title="Ratings", description="")
    website_message_ids: Optional[List[int]] = Field(None, title="Website Messages", description="Website communication history")
    packaging_ids: Optional[List[int]] = Field(None, title="Product Packages", description="Gives the different ways to package the same product.")
    seller_ids: Optional[List[int]] = Field(None, title="Vendors", description="")
    variant_seller_ids: Optional[List[int]] = Field(None, title="Variant Seller", description="")
    attribute_line_ids: Optional[List[int]] = Field(None, title="Product Attributes", description="")
    valid_product_template_attribute_line_ids: Optional[List[int]] = Field(None, title="Valid Product Attribute Lines", description="")
    product_variant_ids: List[int] = Field([], title="Products", description="")
    product_document_ids: Optional[List[int]] = Field(None, title="Documents", description="")
    product_tag_ids: Optional[List[int]] = Field(None, title="Product Template Tags", description="")
    image_1920: Optional[Any] = Field(None, title="Image", description="")
    image_1024: Optional[Any] = Field(None, title="Image 1024", description="")
    image_512: Optional[Any] = Field(None, title="Image 512", description="")
    image_256: Optional[Any] = Field(None, title="Image 256", description="")
    image_128: Optional[Any] = Field(None, title="Image 128", description="")
    activity_state: Optional[Any] = Field(None, title="Activity State", description="Status based on activities\nOverdue: Due date is already passed\nToday: Activity date is today\nPlanned: Future activities.")
    activity_type_icon: Optional[str] = Field(None, title="Activity Type Icon", description="Font awesome icon e.g. fa-tasks")
    activity_date_deadline: Optional[str] = Field(None, title="Next Activity Deadline", description="")
    my_activity_date_deadline: Optional[str] = Field(None, title="My Activity Deadline", description="")
    activity_summary: Optional[str] = Field(None, title="Next Activity Summary", description="")
    activity_exception_decoration: Optional[Any] = Field(None, title="Activity Exception Decoration", description="Type of the exception activity on record.")
    activity_exception_icon: Optional[str] = Field(None, title="Icon", description="Icon to indicate an exception activity.")
    message_is_follower: Optional[bool] = Field(None, title="Is Follower", description="")
    has_message: Optional[bool] = Field(None, title="Has Message", description="")
    message_needaction: Optional[bool] = Field(None, title="Action Needed", description="If checked, new messages require your attention.")
    message_needaction_counter: Optional[int] = Field(None, title="Number of Actions", description="Number of messages requiring action")
    message_has_error: Optional[bool] = Field(None, title="Message Delivery error", description="If checked, some messages have a delivery error.")
    message_has_error_counter: Optional[int] = Field(None, title="Number of errors", description="Number of messages with delivery error")
    message_attachment_count: Optional[int] = Field(None, title="Attachment Count", description="")
    message_has_sms_error: Optional[bool] = Field(None, title="SMS Delivery error", description="If checked, some messages have a delivery error.")
    sequence: Optional[int] = Field(None, title="Sequence", description="Gives the sequence order when displaying a product list")
    description: Optional[Any] = Field(None, title="Description", description="")
    description_purchase: Optional[Any] = Field(None, title="Purchase Description", description="")
    description_sale: Optional[Any] = Field(None, title="Sales Description", description="A description of the Product that you want to communicate to your customers. This description will be copied to every Sales Order, Delivery Order and Customer Invoice/Credit Note")
    type: Optional[Any] = Field(None, title="Type", description="")
    list_price: Optional[Any] = Field(None, title="Sales Price", description="Price at which the product is sold to customers.")
    standard_price: Optional[Any] = Field(None, title="Cost", description="Value of the product (automatically computed in AVCO).\n        Used to value the product when the purchase cost is not known (e.g. inventory adjustment).\n        Used to compute margins on sale orders.")
    volume: Optional[Any] = Field(None, title="Volume", description="")
    volume_uom_name: Optional[str] = Field(None, title="Volume unit of measure label", description="")
    weight: Optional[Any] = Field(None, title="Weight", description="")
    weight_uom_name: Optional[str] = Field(None, title="Weight unit of measure label", description="")
    sale_ok: Optional[bool] = Field(None, title="Can be Sold", description="")
    purchase_ok: Optional[bool] = Field(None, title="Can be Purchased", description="")
    uom_name: Optional[str] = Field(None, title="Unit of Measure Name", description="")
    active: Optional[bool] = Field(None, title="Active", description="If unchecked, it will allow you to hide the product without removing it.")
    color: Optional[int] = Field(None, title="Color Index", description="")
    is_product_variant: Optional[bool] = Field(None, title="Is a product variant", description="")
    product_variant_count: Optional[int] = Field(None, title="# Product Variants", description="")
    barcode: Optional[str] = Field(None, title="Barcode", description="")
    default_code: Optional[str] = Field(None, title="Internal Reference", description="")
    pricelist_item_count: Optional[int] = Field(None, title="Number of price rules", description="")
    product_document_count: Optional[int] = Field(None, title="Documents Count", description="")
    can_image_1024_be_zoomed: Optional[bool] = Field(None, title="Can Image 1024 be zoomed", description="")
    has_configurable_attributes: Optional[bool] = Field(None, title="Is a configurable product", description="")
    product_tooltip: Optional[str] = Field(None, title="Product Tooltip", description="")
    priority: Optional[Any] = Field(None, title="Favorite", description="")
    product_properties: Optional[Any] = Field(None, title="Properties", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")

