
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class ProductDocumentModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    name: str = Field("", title="Name", description="")
    type: Any = Field(None, title="Type", description="You can either upload a file from your computer or copy/paste an internet link to your file.")
    ir_attachment_id: int = Field(0, title="Related attachment", description="")
    res_id: Optional[Any] = Field(None, title="Resource ID", description="")
    company_id: Optional[int] = Field(None, title="Company", description="")
    original_id: Optional[int] = Field(None, title="Original (unoptimized, unresized) attachment", description="")
    website_id: Optional[int] = Field(None, title="Website", description="")
    theme_template_id: Optional[int] = Field(None, title="Theme Template", description="")
    voice_ids: Optional[List[int]] = Field(None, title="Voice", description="")
    active: Optional[bool] = Field(None, title="Active", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")
    description: Optional[Any] = Field(None, title="Description", description="")
    res_name: Optional[str] = Field(None, title="Resource Name", description="")
    res_model: Optional[str] = Field(None, title="Resource Model", description="")
    res_field: Optional[str] = Field(None, title="Resource Field", description="")
    url: Optional[str] = Field(None, title="Url", description="")
    public: Optional[bool] = Field(None, title="Is public document", description="")
    access_token: Optional[str] = Field(None, title="Access Token", description="")
    raw: Optional[Any] = Field(None, title="File Content (raw)", description="")
    datas: Optional[Any] = Field(None, title="File Content (base64)", description="")
    db_datas: Optional[Any] = Field(None, title="Database Data", description="")
    store_fname: Optional[str] = Field(None, title="Stored Filename", description="")
    file_size: Optional[int] = Field(None, title="File Size", description="")
    checksum: Optional[str] = Field(None, title="Checksum/SHA1", description="")
    mimetype: Optional[str] = Field(None, title="Mime Type", description="")
    index_content: Optional[Any] = Field(None, title="Indexed Content", description="")
    local_url: Optional[str] = Field(None, title="Attachment URL", description="")
    image_src: Optional[str] = Field(None, title="Image Src", description="")
    image_width: Optional[int] = Field(None, title="Image Width", description="")
    image_height: Optional[int] = Field(None, title="Image Height", description="")
    key: Optional[str] = Field(None, title="Key", description="")

