
from pydantic import BaseModel, Field
from typing import Optional, List, Any

class ServerActionsModel(BaseModel):
    id: Optional[int] = Field(None, title="ID", description="")
    name: str = Field("", title="Action Name", description="")
    type: str = Field("", title="Action Type", description="")
    binding_type: Any = Field(None, title="Binding Type", description="")
    usage: Any = Field(None, title="Usage", description="")
    state: Any = Field(None, title="Type", description="Type of server action. The following values are available:\n- 'Update a Record': update the values of a record\n- 'Create Activity': create an activity (Discuss)\n- 'Send Email': post a message, a note or send an email (Discuss)\n- 'Send SMS': send SMS, log them on documents (SMS)- 'Add/Remove Followers': add or remove followers to a record (Discuss)\n- 'Create Record': create a new record with new values\n- 'Execute Code': a block of Python code that will be executed\n- 'Send Webhook Notification': send a POST request to an external system, also known as a Webhook\n- 'Execute Existing Actions': define an action that triggers several other server actions")
    xml_id: Optional[str] = Field(None, title="External ID", description="ID of the action if defined in a XML file")
    binding_model_id: Optional[int] = Field(None, title="Binding Model", description="Setting a value makes this action available in the sidebar for the given model.")
    model_id: int = Field(0, title="Model", description="Model on which the server action runs.")
    crud_model_id: Optional[int] = Field(None, title="Record to Create", description="Specify which kind of record should be created. Set this field only to specify a different model than the base model.")
    link_field_id: Optional[int] = Field(None, title="Link Field", description="Specify a field used to link the newly created record on the record used by the server action.")
    groups_id: Optional[List[int]] = Field(None, title="Allowed Groups", description="Groups that can execute the server action. Leave empty to allow everybody.")
    update_field_id: Optional[int] = Field(None, title="Field to Update", description="")
    update_related_model_id: Optional[int] = Field(None, title="Update Related Model", description="")
    template_id: Optional[int] = Field(None, title="Email Template", description="")
    activity_type_id: Optional[int] = Field(None, title="Activity Type", description="")
    activity_user_id: Optional[int] = Field(None, title="Responsible", description="")
    sms_template_id: Optional[int] = Field(None, title="SMS Template", description="")
    available_model_ids: Optional[List[int]] = Field(None, title="Available Models", description="")
    child_ids: Optional[List[int]] = Field(None, title="Child Actions", description="Child server actions that will be executed. Note that the last return returned action value will be used as global return value.")
    webhook_field_ids: Optional[List[int]] = Field(None, title="Webhook Fields", description="Fields to send in the POST request. The id and model of the record are always sent as '_id' and '_model'. The name of the action that triggered the webhook is always sent as '_name'.")
    partner_ids: Optional[List[int]] = Field(None, title="Partner", description="")
    help: Optional[Any] = Field(None, title="Action Description", description="Optional help text for the users with a description of the target view, such as its usage and purpose.")
    binding_view_types: Optional[str] = Field(None, title="Binding View Types", description="")
    display_name: Optional[str] = Field(None, title="Display Name", description="")
    create_uid: Optional[int] = Field(None, title="Created by", description="")
    create_date: Optional[str] = Field(None, title="Created on", description="")
    write_uid: Optional[int] = Field(None, title="Last Updated by", description="")
    write_date: Optional[str] = Field(None, title="Last Updated on", description="")
    sequence: Optional[int] = Field(None, title="Sequence", description="When dealing with multiple actions, the execution order is based on the sequence. Low number means high priority.")
    model_name: Optional[str] = Field(None, title="Model Name", description="")
    code: Optional[Any] = Field(None, title="Python Code", description="Write Python code that the action will execute. Some variables are available for use; help about python expression is given in the help tab.")
    crud_model_name: Optional[str] = Field(None, title="Target Model Name", description="")
    update_path: Optional[str] = Field(None, title="Field to Update Path", description="Path to the field to update, e.g. 'partner_id.name'")
    update_field_type: Optional[Any] = Field(None, title="Field Type", description="")
    update_m2m_operation: Optional[Any] = Field(None, title="Many2many Operations", description="")
    update_boolean_value: Optional[Any] = Field(None, title="Boolean Value", description="")
    value: Optional[Any] = Field(None, title="Value", description="For Python expressions, this field may hold a Python expression that can use the same values as for the code field on the server action,e.g. `env.user.name` to set the current user's name as the value or `record.id` to set the ID of the record on which the action is run.\n\nFor Static values, the value will be used directly without evaluation, e.g.`42` or `My custom name` or the selected record.")
    evaluation_type: Optional[Any] = Field(None, title="Value Type", description="")
    resource_ref: Optional[Any] = Field(None, title="Record", description="")
    selection_value: Optional[int] = Field(None, title="Custom Value", description="")
    value_field_to_show: Optional[Any] = Field(None, title="Value Field To Show", description="")
    webhook_url: Optional[str] = Field(None, title="Webhook URL", description="URL to send the POST request to.")
    webhook_sample_payload: Optional[Any] = Field(None, title="Sample Payload", description="")
    mail_post_autofollow: Optional[bool] = Field(None, title="Subscribe Recipients", description="")
    mail_post_method: Optional[Any] = Field(None, title="Send Email As", description="")
    activity_summary: Optional[str] = Field(None, title="Title", description="")
    activity_note: Optional[Any] = Field(None, title="Note", description="")
    activity_date_deadline_range: Optional[int] = Field(None, title="Due Date In", description="")
    activity_date_deadline_range_type: Optional[Any] = Field(None, title="Due type", description="")
    activity_user_type: Optional[Any] = Field(None, title="User Type", description="Use 'Specific User' to always assign the same user on the next activity. Use 'Dynamic User' to specify the field name of the user to choose on the record.")
    activity_user_field_name: Optional[str] = Field(None, title="User Field", description="")
    sms_method: Optional[Any] = Field(None, title="Send SMS As", description="")
    website_path: Optional[str] = Field(None, title="Website Path", description="")
    website_url: Optional[str] = Field(None, title="Website Url", description="The full URL to access the server action through the website.")
    website_published: Optional[bool] = Field(None, title="Available on the Website", description="A code server action can be executed from the website, using a dedicated controller. The address is <base>/website/action/<website_path>. Set this field as True to allow users to run this action. If it is set to False the action cannot be run through the website.")

